language: java
dist: xenial
sudo: false
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "chabala"
    token:
      secure: "pLO2/TcsZaMYgSiJz6BOGun/ILCpaAaAe/huUhylb+ayVFR+4IK5aWujigRV6KK0K62hq133Z1ab80cpEPaDL3eLkC2p+BpUjild9Ipc1ts8e+HenJaAxYqtMj7H2RP5whMlW1DMDrGk3+MecKA1rd80v5oAI3+dWBguwRk8fzlRUvXl0731bicFkFpqP7GTv8IB0dtKY4u/VDc8w6UbMAyo67OzDANEtgYPxus0ZtHqSV+YAMBeGd3HN99JhxxFk5rg/t1bgHmF88A3CHiZyBzGS8Qn3J1XRcapnnKmJitsXXZqRwBIcOjZ8hEUJYHcQFpsWghTUlbzelpnsEKSE5mth4Um416uFYLCZw3TaVYFID7o1AGI87G+6gUb2XWEj/ln90UfenX2hzsFJ10ybvPmmebAjBxnn3vt6NrWcBuObARbG4Ptuzzf/+P3ucNiPt5eZpT1L+sE3VwAUcJnSs1rBKy6id7ZlCHWdXLGlRUmxGCfvJ9up41AQ6v2yuI9mtxsg4J/4mYOdDxgpx2EblnYELoX0VMd2Uvkmt4nwLZ1KjZF+D2t6iMAJ/WWdD/8h3I49iuSH4/9kihHafh/K7MCKLWoY8daZU4pY4Xbu0LFM/tX5lNlCnixEI40rqQFbOqTwL7x2vacz3tnDLZ0VefpjYIxsZ+3BAFByKTYcNs="
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script: mvn clean verify jacoco:report coveralls:report sonar:sonar
