name: Build

on:
  push:
    branches: [ master ]
  pull_request: # all pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set up Java 8'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'maven'

      - name: 'Build'
        run: |
          mvn --batch-mode verify jacoco:report coveralls:report \
          -DrepoToken=${{ secrets.COVERALLS_TOKEN }} -DpullRequest=${{ github.event.number }}

      - name: 'Upload directory to pass to next job'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .
  sonar:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Restore directory from build'
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .

      - name: 'Set up Java 11'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'

      - name: 'Sonar'
        run: |
          mvn --batch-mode sonar:sonar \
          -Dsonar.organization=chabala -Dsonar.projectKey=org.chabala.brick:brick-control-lab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
