name: Build

on:
  push:
    branches: [ master ]
  pull_request: # all pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set up Java 8'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'maven'

      - name: 'Build'
        run: |
          mvn --batch-mode verify jacoco:report coveralls:report sonar:sonar \
          -DrepoToken=${{ secrets.COVERALLS_TOKEN }} -DpullRequest=${{ github.event.number }} \
          -Dsonar.organization=chabala -Dsonar.projectKey=org.chabala.brick:brick-control-lab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
